version: '3.8'

services:
  vuljndi-app:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: vuljndi-app:latest
    container_name: vuljndi-app
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    restart: unless-stopped
    networks:
      - vuljndi-network

networks:
  vuljndi-network:
    driver: bridge