version: '3.8'

services:
  vuljndi-app:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: vuljndi-app:latest
    container_name: vuljndi-app
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      vuljndi-network:
        ipv4_address: 10.0.0.2

  hack:
    build:
      context: .
      dockerfile: Dockerfile.hack
    image: hack:latest
    container_name: hack
    ports:
      - "1099:1099"
      - "1389:1389"
      - "8180:8180"
    networks:
      vuljndi-network:
        ipv4_address: 10.0.0.3

networks:
  vuljndi-network:
    name: vuljndi-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24

